import { Container, Header } from "@/components/shared";
import { cn } from "@/lib/utils";
import type { Metadata } from "next";

export const metadata: Metadata = {
  title: "Next pizza | Корзина",
  description: "Generated by create next app",
};

export default function CheckoutLayout({
  children,
  className
}: Readonly<{
  children: React.ReactNode;
  className: string
}>) {
  return (
    <main className={cn("min-h-screen bg-[#F4F1EE]", className)}>
        <Header hasSearch={false} hasCart={false} className="border-gray-190"/>
        <Container>
            {children}
        </Container>
    </main>
  )
}
