import type { Metadata } from "next";


export const metadata: Metadata = {
  title: "Next pizza",
  description: "Generated by create next app",
};

export default function DashboardLayout({
  children,
  className
}: Readonly<{
  children: React.ReactNode;
  className: string
}>) {
  return (
    <html lang="en">
      <body className={className}>
        <main className="min-h-screen">
          <h1>123</h1>
        </main>
        </body>
    </html>
  );
}
